const REDIS_CACHE_TIME = 3600 * 24

const MYNTRA_SCRAPE_PAGE = 5
const FLIPKART_SCRAPE_PAGE = 10
const AMAZON_SCRAPE_PAGE = 5

module.exports = { REDIS_CACHE_TIME, MYNTRA_SCRAPE_PAGE, FLIPKART_SCRAPE_PAGE, AMAZON_SCRAPE_PAGE }