const isClothingProduct = (product: string) => {
  const clothingKeywords = [
    "shirt",
    "shirts",
    "t-shirt",
    "t-shirts",
    "blouse",
    "blouses",
    "top",
    "tops",
    "dress",
    "dresses",
    "skirt",
    "skirts",
    "pants",
    "trousers",
    "jeans",
    "shorts",
    "jacket",
    "jackets",
    "coat",
    "coats",
    "sweater",
    "sweaters",
    "hoodie",
    "hoodies",
    "sweatshirt",
    "sweatshirts",
    "suit",
    "suits",
    "tie",
    "ties",
    "scarf",
    "scarves",
    "hat",
    "hats",
    "cap",
    "caps",
    "gloves",
    "socks",
    "shoes",
    "boots",
    "sandals",
    "heels",
    "flats",
    "sneakers",
    "trainers",
    "flip flops",
    "swimsuit",
    "saare",
    "saares",
  ];
  return clothingKeywords.some((keyword) =>
    product.toLowerCase().includes(keyword)
  );
};

export default isClothingProduct;
